### PR TITLE
Maven support + UiBinder wrapper

### PR DESCRIPTION
**Pull request by chitzkoy**
Maven support added.
Ace replaced by noconflict version (it was important for huge projects).
Added UiBinder wrapper (AceEditorWidget).
Setting a useWorker flag moved to separate method.

for building demo
1. install [Maven](http://maven.apache.org/);
2. go to project directory;
3. execute `cd AceGWT/AceGWTDemo`
4. do `mvn gwt:run`

### CODE REVIEW

**Comment by takapa** [comment]
I would have much preferred a much more granular set of pull requests than this mammoth set which is nigh on impossible to vet without investing a large amount of time, particularly with the changeover to the noconflict version, which may or may not harbour regressions outside of the wrapper code changes.

I also notice that you remove the Eclipse .project file. What was your reasoning behind this?

**Comment by chitzkoy** [comment]
You are right, Chris - set of small pull requests are better than one mammoth pull request. What can I do now in this case? 

And yes, I removed the Eclipse .project file because it not needed for Maven structure and I was confident, that the Eclipse understands Maven project object model out of the box (now I stand corrected).

**Comment by rsutormin** [comment]
It looks like you changed structure of folders inside AceGWT project. For instance you moved AceGWT/src/edu/ycp/cs/dh/acegwt/client/* into AceGWT/src/main/java/edu/ycp/cs/dh/acegwt/client/*, and AceGWT/src/edu/ycp/cs/dh/acegwt/public/* into AceGWT/src/main/resources/edu/ycp/cs/dh/acegwt/public/* . And similar change was done for AceGWTDemo. What is the purpose of it?

**Comment by chitzkoy** [comment]
@rsutormin, the main purpose of it - unification of projects structure that built with one framework.
In this case I use [GWT module archetype](http://mojo.codehaus.org/gwt-maven-plugin/user-guide/archetype.html).

**Comment by takapa** [comment]
OK, here is my opinion.

First, please can you sign the MIT License declarion form at the following URL:

https://github.com/daveho/AceGWT/issues/18

We will be using this going forward for all commiters (past and present).

Secondly, I don't think we can merge such a huge pull request at this time. There are just too many structural changes alongside functionality changes. As a rule of thumb, you should do one thing at a time before checking in a change. That way, the change can be evaluated in isolation.

I suggest, you keep your branch seperate, and try to merge in your changes into the main branch, one pull request at a time, finally ending in the maven structural changes.

Also, library updates for Ace should be checked in in an atomic pull request. Such pull requests tend to be very noisy. Isolate that, isolate the maven structural changes, isolate the UI binder changes, and submit one at a time, least radical first.

That is my own opinion on this, Dave and Roman may have different opinions.

**Comment by chitzkoy** [comment]
@takapa, I appreciate your opinion and I'll take it into consideration in my future pull requests.

**Pull request closed without merging**
