### PR TITLE
Added focus and getLineCount methods.

### PR DESCRIPTION
**Pull request by hoffman373**
I exposed the focus and getLineCount methods on the AceEditor component.

### CODE REVIEW

**Comment by rsutormin** [comment]
Hi, can we ask you to add some demo code into https://github.com/daveho/AceGWT/blob/master/AceGWTDemo/src/edu/ycp/cs/dh/acegwt/client/demo/client/AceGWTDemo.java using these methods?

**Comment by hoffman373** [comment]
I have added changes to the AceGWTDemo.java file that supports both of the methods. If you have something specific in mind for the demo, please ask.

**Comment by rsutormin** [comment]
Hi hoffman373,
In your second commit you reformatted whole AceGWTDemo.java file. Why did you do that? Can we ask you to fix formatting? Please use tabs instead of spaces and make sure you don't change code lines not related directly to your particular feature change.

**Comment by hoffman373** [comment]
It was a mistake. I'll back it out.

**Pull request merged**
